<?php

namespace AppBundle\Repository;

/**
 * Team_MembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Team_MembersRepository extends \Doctrine\ORM\EntityRepository
{
}
