# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    UserController:
        class: AppBundle\Controller\UserController
        calls:
            - [setContainer, ["@service_container"]]

    app.service.google_contacts_api:
        class: AppBundle\Service\GoogleContactsService
        arguments: ['@service_container']

    app.service.busyslots:
        class: AppBundle\Service\BusySlotsService
        arguments: ['@service_container',  '@doctrine.orm.entity_manager' ]

    app.service.disposteams:
        class: AppBundle\Service\DisposTeamService
        arguments: ['@service_container', '@doctrine.orm.entity_manager' ]

    app.service.superpositionkiller:
        class: AppBundle\Service\SuperpositionKillerService

    app.service.accesstoken:
        class: AppBundle\Service\AccessTokenService
        arguments: ['@service_container', '@doctrine.orm.entity_manager' ]
